---
name: Test code

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
services:
    postgres:
        image: postgis/postgis
        env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: github_actions
        ports:
            - 5432:5432
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
jobs:
  test_core:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name:
        Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "django-geojson [field]"
    - name: Run tests
      run: |
        export DJANGO_SETTINGS_MODULE=seshat.settings.local
        python manage.py test seshat.apps.core --keepdb