---
name: test_code

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test_core:
    strategy:
      matrix:
        python-version: ['3.8']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: docker.pkg.github.com/edwardchalstrey1/seshat/tests-image:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
          PGDATA: '/var/lib/postgresql/data/db-files/'
          DJANGO_SETTINGS_MODULE: seshat.settings.local

        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Check PostgreSQL connectivity
      run: |
        docker exec seshat_testing psql -h localhost -U postgres -c 'SELECT 1'
    - name: Run tests
      run: |
        docker exec seshat_testing python3 /seshat/manage.py test seshat.apps.core --keepdb
