---
name: Test code

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  test_core:
    services:
        postgres:
            image: postgis/postgis
            env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: github_actions
            ports:
                - 5432:5432
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name:
        Install dependencies
      run: |
        sudo apt-get install gdal-bin -y
        sudo apt-get install libgdal-dev -y
        sudo apt install libgeos++-dev libgeos3.10.2 -y
        sudo apt install libgeos-c1v5 libgeos-dev libgeos-doc -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "django-geojson [field]"
    - name: Run tests
      run: |
        export DJANGO_SETTINGS_MODULE=seshat.settings.local
        python manage.py test seshat.apps.core --keepdb