---
name: Test code

# Triggers the workflow on push or pull request to dev branch, see test_docker.yml
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test_core:
    strategy:
      matrix:
        python-version: ['3.8']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Pull and run Docker image
      run: |
        docker pull docker.pkg.github.com/edwardchalstrey1/seshat/tests-image:latest
        docker run -d -p 5432:5432 --name postgres docker.pkg.github.com/edwardchalstrey1/seshat/tests-image:latest
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check PostgreSQL connectivity
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -c 'SELECT 1'
    - name: Set max_locks_per_transaction for the current session
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d github_actions -c 'SET max_locks_per_transaction = 256;'
    - name: Run tests
      run: |
        export DJANGO_SETTINGS_MODULE=seshat.settings.local
        python manage.py test seshat.apps.core --keepdb
